version: '3.8'

services:
  db:
    image: bitnami/postgresql:16
    container_name: cdm_database
    restart: always
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
  adminer:
    image: adminer:latest
    container_name: cdm_adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  redis:
    container_name: cdm_redis
    image: redis:7-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
  api:
    build: .
    container_name: cdm_api
    image: cdm_api
    env_file: .env
    environment:
      - "USE_DOCKER=true"
      - "DB_HOST=db"
      - "REDIS_HOST=redis"
    depends_on:
      - db
      - redis
    ports:
      - "${API_PORT}:${API_PORT}"
    command: /bin/sh -c "npm run docker:db:migrate && pm2-runtime start ecosystem.config.js"
