export const error_messages = {
	$$_NOT_FOUND: '$0 with the $1 $2 was not found',
	PAGE_OUT_OR_RANGE: 'page parameter $0 is out of range. See _meta in the response',
	QUERY_INCLUDES_EMPTY: 'query.includes must not be empty',
	DUPLICATE_KEYS: 'duplicate keys values violates unique constraint',
	DUPLICATE_EVENT: 'event already exist',
	DUPLICATE_KEY_$$: '$0 already exist',
	NO_UPDATE_CHANGE: 'current values are the same as the previous ones',
	DEVICE_NOT_CONNECTED: 'device $0 is not online or not connected to the server',
	$$_NOT_CONNECTED: '$0 $1 is not online or not connected',
	$$_ALREADY_EXIST: '$0 with $1 already exist',
	$$_ALREADY_DELETED: '$0 with id $1 has already been deleted',
	$$_ALREADY_ACTIVATED: '$0 with $1 $2 is already activated',
	$$_ALREADY_EXECUTED: '$0 $1 has already been executed',
	$$_ALREADY_EXECUTING: '$0 $1 is currently processing',
	REQUEST_TO_DEVICE: 'The request to the device $0 failed',
	COMMAND_NOT_FOUND: 'The command $1 not found for terminal.id $2',
	SERVICE_NOT_STARTED: 'The service $0 was not enable to start',
	SERVICE_$$_NOT_AVAILABLE: 'The service $0 is not available',
	APPLICATION_NOT_REGISTERED: 'The application $0 is not registered on this device',
	// 'id_user_not_found': 'Id user does not exist',
	// 'route_not_found': "'{}' not found",
	// 'unknown_error': 'An unknown error appear. An email was send to an admin',
	// 'user_not_found': 'User not found with this {}',
	// 'access_forbidden': 'User not have the permission to access this route',
	// 'token_expired': 'The token you submitted has expired',
	// 'incorrect_email_or_password': 'Your email or your password is incorrect',
	// 'no_ressource_found': 'No ressource was found with id {}',
}

export default { error_messages }
